# Site settings
title: Carlo Nicolini
email: "carlo.nicolini@iit.it"
description: "Personal blog about science, programming, statistical mechanics, network theory and neuroimaging"
baseurl: "" 
url: "https://carlonicolini.github.io"
github_username:  carlonicolini
twitter_username: carlonicolini84
google-analytics: UA-90756713-1
# Build settings
markdown: kramdown
keep_files: [MathJax]
enable_disqus: true 
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemapplugin
social:
  name: Carlo Nicolini
  links:
    - https://twitter.com/carlonicolini84
    - https://www.linkedin.com/in/carlo-nicolini
    - https://github.com/carlonicolini
