# Site settings
title: Carlo Nicolini
email: "carlo.nicolini@iit.it"
description: "My personal website"
baseurl: "" 
url: "http://carlonicolini.github.io"
github_username:  carlonicolini

# Build settings
markdown: kramdown
