# Site settings
title: Carlo Nicolini
email: "carlo.nicolini@iit.it"
description: "My small place."
baseurl: "" 
url: "http://carlonicolini.github.io"
github_username:  carlonicolini
twitter_username: carlonicolini84
google-analytics: UA-90756713-1
# Build settings
markdown: kramdown
keep_files: [MathJax]
