# Site settings
title: 'Carlo Nicolini'
email: "c.nicolini@ipazia.com"
description: "Personal blog about artificial intelligence, coding, statistical physics, network theory and science in general"
logo: "/static/img/foto_nicolini.jpeg"
baseurl: "" 
url: "https://carlonicolini.github.io"
github_username:  carlonicolini
google-analytics: UA-90756713-1
collections:
- well-known
# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6
keep_files: [MathJax]
enable_disqus: true 
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-scholar
  
social:
  name: Carlo Nicolini
  links:
    - https://www.linkedin.com/in/carlo-nicolini
    - https://github.com/carlonicolini
