# Site settings
title: 'Carlo Nicolini'
email: "c.nicolini@ipazia.com"
description: "Personal blog about artificial intelligence, coding, statistical physics, network theory and science in general"
baseurl: "" 
url: "https://carlonicolini.github.io"
github_username:  carlonicolini
collections:
- well-known
# Build settings
livereload: true
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6
keep_files: [MathJax]
enable_disqus: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-scholar

exclude:
  - Gemfile
  - Gemfile.lock
  - .gstack/
  - '_site'

social:
  name: Carlo Nicolini
  links:
    - https://www.linkedin.com/in/carlo-nicolini
    - https://github.com/carlonicolini

scholar:
  style: apa                  # Citation style (e.g., apa, ieee, chicago)
  locale: en                  # Locale used for formatting
  sort_by: year               # Sort bibliography by year
  order: descending           # Newest first
  source: ./_bibliography     # Where your .bib files are located
  bibliography: biblio.bib    # The default .bib file name
  bibliography_template: "{{reference}}" # Template for formatting bibliography entries