# Site settings
title: Carlo Nicolini
email: "carlo.nicolini@iit.it"
description: "My small place."
baseurl: "" 
url: "https://carlonicolini.github.io"
github_username:  carlonicolini
twitter_username: carlonicolini84

# Build settings
markdown: kramdown
keep_files: [MathJax]
enable_disqus: true
plugins:
  - jekyll-seo-tag
social:
  name: Carlo Nicolini
  links:
    - https://twitter.com/carlonicolini84
    - https://www.linkedin.com/in/carlo-nicolini
    - https://github.com/carlonicolini
